apiVersion: apps.kruise.io/v1alpha1
kind: RolloutDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: rolloutdefinition-deployment
spec:
  controlResource:
    apiVersion:  apps/v1
    resource: deployments
  path:
    specPath:
      paused: .spec.paused
      patition: .spec
      maxUnavailable: .spec.strategy.rollingUpdate.maxUnavailable
    statusPath:
      replicas: .status.replicas
      readyReplicas: .status.readyReplicas
      currentReplicas: .status.currentReplicas
      updatedReplicas: .status.updatedReplicas
      observedGeneration: .status.observedGeneration
      conditions: .status.conditions

