apiVersion: apps.kruise.io/v1alpha1
kind: RolloutDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: rolloutdefinition-deployment
spec:
  controlResource:
    apiVersion:  extensions/v1beta1
    resource: Deployment
  specPath:
    paused: .spec.paused
    partitions:
    maxUnavailable: .spec.strategy.rollingUpdate.maxUnavailable
  statusPath:
    replicas: .status.replicas
    readyReplicas: .status.readyReplicas
    updatedReplicas: .status.updatedReplicas
    observedGeneration: .status.observedGeneration
    conditions: .status.conditions
